
name: Build , push docker image to digial ocean cluster to test

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
  workflow_dispatch:

env:
  NAME_SPACE: test
  EXT_PORT: 8080
  INT_PORT: 8080
  IMAGE_NAME: ndemeyvan/express_app_test

jobs:
#   Nom du job 1 ou +sieur
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
#     Checkou sur le code actuel
    - name: Checkout to the actual code
      uses: actions/checkout@v3 
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm install
    - run: npm run build --if-present
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
# # # # # # # # # # # # # # Test

  test:
    needs: build 
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
      - name: Test docker image
      - run: docker run -d -p ${{env.EXT_PORT}}:${{env.INT_PORT}} --name  ${{ env.IMAGE_NAME }}  ${{ env.IMAGE_NAME }}
      - run: sleep 4
      - run: curl localhost:${{env.EXT_PORT}} | grep "Hello"

# # # # # # # # # # # # # # Deployment
  deploy: 
    needs: test 
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
    - name: Set up kubectl
      uses: matootie/dokube@v1.4.0
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: ${{ secrets.CLUSTER_NAME }}

    - name: Checkout to the actual code
      uses: actions/checkout@v3

    # Run any kubectl commands you want!
    - name: Create namespace
      run: kubectl create namespace ${{ env.NAME_SPACE }} | echo "Name space already exist"
    - name: restart deployment
      run: kubectl -n ${{ env.NAME_SPACE }} rollout restart deploy | echo "Empty deployment"
    - name: Apply all k8s object
      run: kubectl -n test apply -f k8s/


