
name: Build , push docker image to digial ocean cluster to test

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
  workflow_dispatch:

jobs:
#   Nom du job 1 ou +sieur
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
#     Checkou sur le code actuel
    - name: Checkout to the actual code
      uses: actions/checkout@v3 
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm install
    - run: npm run build --if-present
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: ndemeyvan/express_app_test
        tags: v1, latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  deploy: 
    needs: build 
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
      # Set up the Kubernetes CLI with your DigitalOcean Kubernetes cluster.
    - name: Set up kubectl
      uses: matootie/dokube@v1.4.0
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: ${{ secrets.CLUSTER_NAME }}

    - name: Checkout to the actual code
      uses: actions/checkout@v3

    # Run any kubectl commands you want!
    - name: Get All Cluster information
      run: kubectl get all
    - name: Create namespace
      run: kubectl create namespace test | echo "Name space already exist"
    - name: Apply all k8s object
      run: kubectl -n test apply -f k8s/


